osx_image: xcode9

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: osx
    - os: linux

cache:
  directories:
  - node_modules
  - $HOME/Library/Caches/electron
  - $HOME/Library/Caches/electron-builder

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils
      - graphicsmagick
      - xz-utils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.1.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
- yarn install
- yarn add electron-builder@next --dev # force install next version to test electron-builder

script:
- yarn dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
